// Configuration model for the live "Login Designer" demo — shows how flexibly a
// Dynamic-powered sign-in can be composed and styled.

export type LoginLayout = "centered" | "split" | "compact";
export type LoginTheme = "midnight" | "aurora" | "light";

export interface LoginConfig {
  layout: LoginLayout;
  theme: LoginTheme;
  accent: string;
  brandName: string;
  tagline: string;
  methods: {
    email: boolean;
    social: boolean;
    wallets: boolean;
    passkey: boolean;
  };
  socialAbove: boolean; // show social above email
  collapseWallets: boolean; // one "Continue with a wallet" button vs. full list
}

// Bundled brand logos live in public/logos/ (generated by scripts/gen-logos.mjs).
const LOGO = (file: string) => `${import.meta.env.BASE_URL}logos/${file}.svg`;
// Official Fireblocks logomark from the brand asset bucket (Navy — for white chip).
const FIREBLOCKS_LOGO =
  "https://fireblocks-logos-us-east-2.s3.us-east-2.amazonaws.com/Brand_PublicRepo/Logos/Logomark-Network_Navy.svg";

// Real Dynamic social providers (Dashboard → Social Providers).
export const SOCIAL_PROVIDERS = [
  { id: "google", label: "Google", logo: LOGO("google") },
  { id: "microsoft", label: "Microsoft", logo: LOGO("microsoft") },
  { id: "apple", label: "Apple", logo: LOGO("apple") },
  { id: "twitter", label: "X", logo: LOGO("x") },
  { id: "discord", label: "Discord", logo: LOGO("discord") },
  { id: "farcaster", label: "Farcaster", logo: LOGO("farcaster") },
  { id: "github", label: "GitHub", logo: LOGO("github") },
] as const;

// Wallet connect options. Fireblocks is featured first (connects via
// WalletConnect) — a Fireblocks-secured wallet plugs right in.
export interface WalletOption {
  id: string;
  label: string;
  logo: string;
  recommended?: boolean;
  note?: string;
}
export const WALLETS: WalletOption[] = [
  { id: "fireblocks", label: "Fireblocks", logo: FIREBLOCKS_LOGO, recommended: true, note: "via WalletConnect" },
  { id: "metamask", label: "MetaMask", logo: LOGO("metamask") },
  { id: "coinbase", label: "Coinbase Wallet", logo: LOGO("coinbase") },
  { id: "walletconnect", label: "WalletConnect", logo: LOGO("walletconnect") },
  { id: "phantom", label: "Phantom", logo: LOGO("phantom") },
];

export const ACCENTS = ["#863bff", "#4361ee", "#14b8a6", "#ec4899", "#f59e0b"];

export interface LoginPreset {
  id: string;
  label: string;
  description: string;
  config: LoginConfig;
}

export const PRESETS: LoginPreset[] = [
  {
    id: "minimal",
    label: "Minimal",
    description: "Just email — fastest onboarding, zero crypto jargon.",
    config: {
      layout: "centered",
      theme: "midnight",
      accent: "#863bff",
      brandName: "Dynamic Mines",
      tagline: "Dig for gems, dodge the bombs.",
      methods: { email: true, social: false, wallets: false, passkey: false },
      socialAbove: false,
      collapseWallets: false,
    },
  },
  {
    id: "social",
    label: "Social-first",
    description: "One-tap social sign-in with email fallback.",
    config: {
      layout: "centered",
      theme: "aurora",
      accent: "#4361ee",
      brandName: "Dynamic Mines",
      tagline: "Sign in and start playing in seconds.",
      methods: { email: true, social: true, wallets: false, passkey: false },
      socialAbove: true,
      collapseWallets: false,
    },
  },
  {
    id: "web3",
    label: "Web3 / BYO wallet",
    description: "Wallet-first for crypto-native users, split-screen brand.",
    config: {
      layout: "split",
      theme: "midnight",
      accent: "#14b8a6",
      brandName: "Dynamic Mines",
      tagline: "Connect your wallet and play on-chain.",
      methods: { email: true, social: false, wallets: true, passkey: false },
      socialAbove: false,
      collapseWallets: false,
    },
  },
  {
    id: "everything",
    label: "Everything",
    description: "The full menu — social, wallets, email, and passkeys.",
    config: {
      layout: "compact",
      theme: "aurora",
      accent: "#ec4899",
      brandName: "Dynamic Mines",
      tagline: "Your wallet, your way.",
      methods: { email: true, social: true, wallets: true, passkey: true },
      socialAbove: true,
      collapseWallets: true,
    },
  },
];

const STORAGE_KEY = "dynamic-mines-login-config";

export function loadLoginConfig(): LoginConfig {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as LoginConfig;
  } catch {
    /* ignore */
  }
  return PRESETS[0].config;
}

export function saveLoginConfig(config: LoginConfig) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}
