// Compiles contracts/GameVault.sol and writes the ABI + bytecode to
// src/contracts/vault.ts so the app can deploy/interact without a toolchain.
import solc from "solc";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const source = readFileSync("contracts/GameVault.sol", "utf8");

const input = {
  language: "Solidity",
  sources: { "GameVault.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const out = JSON.parse(solc.compile(JSON.stringify(input)));
if (out.errors) {
  const fatal = out.errors.filter((e) => e.severity === "error");
  out.errors.forEach((e) => console.log(e.formattedMessage));
  if (fatal.length) process.exit(1);
}

const c = out.contracts["GameVault.sol"].GameVault;
const abi = c.abi;
const bytecode = "0x" + c.evm.bytecode.object;

mkdirSync("src/contracts", { recursive: true });
const ts = `// AUTO-GENERATED by scripts/compile-vault.mjs — do not edit by hand.
// Source: contracts/GameVault.sol (solc ${solc.version()})
export const VAULT_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const VAULT_BYTECODE = "${bytecode}" as const;
`;
writeFileSync("src/contracts/vault.ts", ts);
console.log(`Wrote src/contracts/vault.ts — bytecode ${bytecode.length} chars`);
